### ISSUE TITLE
多个API轮询

### ISSUE THREAD

**Issue by bingood** [clairelovesgravy/discord-bot-gemini#1]
你好，按说明部署成功了，但是单个API有次数限制，可否增加一个多API轮询的功能呢？

**Comment by clairelovesgravy** [comment]
加了，你更新下repository再试试？

**Comment by clairelovesgravy** [comment]
taking turns to use apis is supported

**Comment by bingood** [comment]
谢谢，试了下没问题，有个小修改，`.env`中的`GEMINI_API_KEY`需要改成`GEMINI_API_KEYS`

**Comment by clairelovesgravy** [comment]
谢谢提醒
